# Generated by Django 3.2.9 on 2022-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=200)),
                ('actor_biography', models.TextField(verbose_name='Биография')),
                ('actor_image', models.ImageField(upload_to='media/', verbose_name='Фото')),
                ('сategory_actor', models.IntegerField(verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('name_category', models.CharField(max_length=50, verbose_name='Имя категории')),
                ('url_category', models.CharField(max_length=50, verbose_name='Url категория')),
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_film', models.CharField(max_length=50, verbose_name='Название фильма')),
                ('image_film', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('year_film', models.CharField(max_length=50, verbose_name='Год фильма')),
                ('сategory_film', models.IntegerField(verbose_name='Категория')),
            ],
        ),
    ]
